### ISSUE TITLE
Work in ^4 bit

### ISSUE THREAD

**Issue by ChiHisLiu** [avarghesein/ActiveX.NET#1]
I change code to not-prefer 32bit. This make the server not run normally. Could have any way to solve it?

**Comment by avarghesein** [comment]
What's the issue you've faced? Could you please provide more details?

**Comment by avarghesein** [comment]
I presume, you can follow [this link](https://mariusbancila.ro/blog/2010/11/04/32-bit-and-64-bit-com-servers/) to work the application properly in 64-bit mode.

In essence; you've to update [RegasmRegisterLocalServer](https://github.com/avarghesein/ActiveX.NET/blob/master/Source/ActiveX.NET/ActiveXServer.NET.Common/ActiveXServerBase.cs) function to update Registry Location while registering COM Servers to support 32/64 bits.

You could also mention the preferred bit (32 or 64, while creating the COM Instance) from your consumer applications like Excel VBA while creating the COM object or in general with registry settings. The same has been mentioned in the aforementioned link.

**Comment by alibeirami** [comment]
Hi,
I Managed to work with x64 config by changing the config of ActiveX.Net.Server and ActiveX.Net.Common Projects to x64. when checking the registery, now it is written to HKEY_CLASSES_ROOT\CLSID instead of HKEY_CLASSES_ROOT\Wow6432Node\CLSID\ 
and x64 Program works seamlessly.

Thanks for awsome project btw.

**Comment by avarghesein** [comment]
Excellent Thank you Alibeirami
