### ISSUE TITLE
Would it be possible to host a persistent C# .NET COM server?

### ISSUE THREAD

**Issue by timmi-on-rails** [avarghesein/ActiveX.NET#5]
Hello,

thanks for the ActiveX.NET library. It is the only example I could get running from all the out-of-process COM .NET servers examples out in the internet.

I hope you can guide me in the right direction, whether the following is possible using your ActiveX.NET.
Took me two days so far and I still have no working solution.... frustrating.

**What I have got working so far?**
I have created my own ComVisible .NET assembly and called it from other native applications (Delphi).
I also added manifests to allow a side-by-side configuration of the .NET DLL, because I have to avoid global registration as this requires administrator rights, which might not be available at the install target.

**Why is the in-proc DLL not enough for my interop needs?**
My .NET DLL is using another proprietary framework, which requires a UI message queue (Winforms or WPF) running. Since my .NET C# COM DLL should be a wrapper around the frameworks functionality, I would have to create an extra layer for each ComVisible class, that dispatches all method calls to the Dispatcher/message queue and also encapsulate a class that has the same properties/methods, but is created on the UI thread. While this is possible it will bloat my code for every single class/property/method. Since the framework classes are not ComVisible I cannot expose them directly, so I need a layer of indirection anyway. But another layer for synchronization/thread affinity is what I want to avoid.

**What I ideally want is:**
A ActiveX.NET process with its Winforms message queue that gets started either manually by my client (Delphi) application or that starts automatically when the COM client connects the first time. If I understand correctly you have some logic in the server that shuts it down, when its not needed anymore. So I have to make sure it keeps running, because I want to keep the frameworks state, even if I have currently no COM objects at hand. Maybe I could fake this behaviour with keeping one COM object globally in my Delphi application.
Ideally I need the server to run in a side-by-side configuration. I have no clue how to achieve this. Currently you are registering the server with "RegistrationServices". Do you know of a side-by-side solution?

I would be really thankful if you tell me if ActiveX.NET is the right starting point and if not, maybe you can guide me to another solution to my problem? It is possible that I am overlooking some really simple alternative. Thanks

**Comment by avarghesein** [comment]
If I understood correctly, you need (to make sure ActiveX.net keeps running, because I want to keep the frameworks state, even if I have currently no COM objects at hand).So I suggest you to open ActiveX.net server on the very first invocation, and keep it there forever. A simple fix to [ActiveXServerContext.cs](https://github.com/avarghesein/ActiveX.NET/blob/master/Source/ActiveX.NET/ActiveX.NET.Server/ActiveXServerContext.cs) can do the trick.

i.e In the function (public int Unlock()), you could comment out (ExitThread()) call, which makes the server running forever. Simply FORK the repo and have your customisation there.

Regarding (>>Ideally I need the server to run in a side-by-side configuration.), I'm not sure about what you have meant. Are you mentioning to run both X64 and X86 version of ActiveXServer to be run in parallel?

**Comment by timmi-on-rails** [comment]
@avarghesein Thank you for your prompt response.

Side-by-Side config (https://docs.microsoft.com/en-us/windows/desktop/sbscs/about-side-by-side-assemblies-) is a way that you do not have to register the COM DLL (in-proc), you can just place the .NET DLL in the same folder as the COM Client and you only have to do two things:
- Add assembly manifest to the .NET COM DLL with (mt.exe)
- Change the Manifest of the COM client to include a dependency on the .NET COM DLL

To clarify, does the plugin code run on the same managed thread which has the Winforms main loop?
Because I tryed the following:
1. Create a Windows Form and show it in the ActiveX.NET.Server
2. Store Form instance inside a static field, that is accesible from a plugin
3. In the plugin query form.InvokeRequired, which should indicate, whether I am on UI thread or not. 

And it says "true"... Which means I am not on the UI thread, so I conclude the plugin methods are not run through the winforms message queue?

**Comment by avarghesein** [comment]
I presume you're mentioning about registrationless COM invocation through Manifests (_May only applicable for InProc COM servers only_). But ActiveX.NET completely rely on the traditional COM model of keeping entries in registry under ClassIDs, as it is an **OutofProc EXE** Server relies on COM API (CoRegisterClassObject: this requires classes are kept on registry ). So I'm not sure, this may be easy with EXE Servers.

Regarding (conclude the plugin methods are not run through the winforms message queue?), I may need to check. Do you've the demo code for this?

**Comment by timmi-on-rails** [comment]
Okay, I don't have demo code ready, but my steps are the following:
- Check out the master of your repo
- Add the line `MessageBox.Show($"UI ManagedThreadId: {Thread.CurrentThread.ManagedThreadId}");` 
right before the `activeXContext.Run();` line in the `Program.cs`
- In the plugin return `$"Hello World ManagedThreadId: {Thread.CurrentThread.ManagedThreadId}"` instead of `"Hello World"`
- And add a constructor to the `class SimpleObject`:
`public SimpleObject()	{	MessageBox.Show($"Constructor ManagedThreadId: {Thread.CurrentThread.ManagedThreadId}");	}`

I tested the plugin with your Excel macro.
What I observe is, that the UI and the constructor show the same ThreadId. However the method call to HelloWorld is run on a separate Thread with different id. 

It is good for my problem, that the constructor runs on the "right" thread, however I really do not understand why that happens? Because you do not manually dispatch the constructor call to the loop.
One reason could be, that COM objects get created, when some responsible function is explicitly called inside the WinForms Application.Run() loop.

Anyway, what I would need is that the HelloWorld call also happens on the UI Thread, without manually dispatching it in every plugin method that I write. Do think that is possible from your knowledge of COM and .NET interop?
(I spent two days getting to know COM and all its flavors and still it seems to me there is much more work required to understand all the details. Thank you for your effort.)

**Comment by avarghesein** [comment]
From my knowledge, MessageBox objects are modal dialogues and handled separately by Win32 runtime. If we would really like to know, we should use Modeless Forms (eg. Form.Show) and see whether it will be running under UI Thread, 

Again my assumption is that, .NET will by default run under MTA (Multi threaded apartment), unless we specify STA for our threads/COM object. So by default any COM call to the Server, may served on a remote RPC thread. But if we specify the thread/COM Object to be STA, the request will be Marshalled and handled in the Parent U thread (at which the message loop is running, i.e activeXContext.Run)

I will try to make a sample on this, probably when i get free. But I presume running our forms (modeless), in the parent UI thread, with tweaking the apartment models (i.e to be in STA). In .NET it seems to have been done through applying certain attributes like [STAThread]. Yet it would be helpful to create a demo, and see how it works.

**Comment by timmi-on-rails** [comment]
I will log the managed thread ID to a file instead. But I doubt that the  use of MessageBox changes the thread where the function argument is evaluated.

**Comment by avarghesein** [comment]
>>use of MessageBox changes the thread (could be true, since Dialogue Boxes are handled specially in Win32). We may need to try out with Modeless Dialogues to assert the thread affinity.

**Comment by avarghesein** [comment]
Hi [timmi](https://github.com/timmi-on-rails), now I've reproduced the issue you've mentioned and confirmed that the methods are running on remote RPC threads, not in UI Thread. This is due to the [default Interface Marshalling Behaviour](https://stackoverflow.com/questions/28628811/how-to-make-make-a-net-com-object-apartment-threaded) of .NET (which prefer MTA over STA for performance reasons).

The solution is  to use STA Marshaller named [StandardOleMarshalObject](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.standardolemarshalobject?view=netframework-4.7.2).

The fix is simple. Simply inherit (ActiveXServerBase) class from (StandardOleMarshalObject). i.e 
`public abstract class ActiveXServerBase : StandardOleMarshalObject, IActiveXServer`

_This has fixed the issue, and I'm seeing the same UI Thread  ID  Everywhere !_

Thanks for this request.

**Comment by timmi-on-rails** [comment]
@avarghesein Thank you for the solution. I tested it and it worked. By the way, I noticed two things using the excel test macro:
- The constructor of SimpleObject is run twice, if the Com Host has been started fresh. If it is already running, then the constructor is run only once as expected.
- There seems to be a timing issue. When you execute the excel macro again and again with some small delay in between, the server seems to shut down during the macro, causing an exception of a missing object.

Now that I have the COM server right, it seems that my Delphi client is not working together with COM RPC. I get messages that the interface is not supported. But I guess this problem is too specific. With normal In-Proc COM DLL I do not have this problem.

**Update:** About the "Interface not supported", I read something (https://www.experts-exchange.com/questions/20809752/Problem-casting-an-interface-from-a-COM-object.html), that I have to register the type libraries separately. So I will try tomorrow and register the type libraries of the plugin DLLs. 

Finally if that should work the only open issue for me is, that I have to register COM as admin and it seems, as you previously said, that it is not possible to have it registration-free. I only found one dirty hack, that I didn't understand.

By the way, in the meantime I developed a solution with an in-proc COM DLL. The DLL starts a Winforms main loop in a separate thread. And then I wrote some automatic code generation that creates wrapper classes around my COM objects and those wrappers dispatch method calls onto the Winforms main loop thread. I tag my COM objects with a custom System.Attribute and generate the wrapper classes with reflection and T4 text templating. This solution has a rather complicated setup, but in the end my classes stay clean, since the wrappers are auto generated in an extra assembly. So I can easily switch to your out-of-proc solution later on with discarding the wrapper project and minimal code changes in the actual DLL.

**Comment by avarghesein** [comment]
Excellent !

> _>> The constructor of SimpleObject is run twice, if the Com Host has been started fresh._ 

I'm keeping an extra object as an MEF template, from which others will be created, when requested. That's might be the reason. 

> _>>When you execute the excel macro again and again with some small delay in between, the server seems to shut down_

Probably we've the autoshutdown feature enabled, which makes the EXE shutdown, if not used for a stipulated time. (I've mentioned a fix earlier, which will make the server up forever)

> _>>I have to register the type libraries separately_

This may be required (especially for OutOfProc Servers), so that proper marshalling can happen between client and server (interfaces and objects). In InProc, this seems to be more relaxed than OutOfProc 

> _>>register COM as admin and it seems, as you previously said, that it is not possible to have it registration-free_

This is required, as oppose to InProc sample (where you've Your Client (EXE) --> InProcServer (DLL), in the same process). And your client's registration manifests can be directly accessed in your DLL's, as they are hosted in your client process.

For OutOfProc sample, its bit complicated (Client (EXE)-->ActiveX.NET(EXE)-->InprocServer(Plugin DLL). As you can see ActiveX.NET is now hosting your DLL's than your client EXE. So to make registrationless  solution to work, You've to update ActiveX.NET exe to have the manifest. If that's the case your original client  EXE will not work, as it requires to talk to another EXE (ActiveX.net), and for that you need explicit Registry Entries. This may not be the one you want.

**Comment by timmi-on-rails** [comment]
Ok, I think now every mystery is solved for me :).

I also can confirm that registering the Plugin typelibraries with e.g. `regasm /tlb Plugin.dll` is necessary to access via Typelibrary COM client. 
However to make it work I had to temporarily comment the `[ComRegisterFunction()]` and `[ComUnregisterFunction()]` attributes in ActiveXServerMTABase.cs. Because they will throw an exception during typelibrary registration, because you wrote them for registration via the server with command line parameter `/regserver`.

It could be worth a try if manifests in the plugins and a dependency from the server to the plugin could make the typelibrary registration obsolete. But then I can also directly embed my COM classes in the server and skip the plugin solution, if I put references anyway.

Thank you again.

**Comment by avarghesein** [comment]
Welcome !

> because you wrote them for registration via the server with command line parameter /regserver
This custom registration is needed anyway (after your register typelib, and reverting to original), as it links the Plugins to OutOfProc (ActiveX.net), than InProc. If you don't they will run as Inproc.

Based on your original query, I've updated the ActiveX.net source ,to support STA, MTA and UserControls. Thanks  for this request!
